WeinhandelDjP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('accounts/', include('accounts.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
]

accounts/urls.py
from django.urls import path

app_name = 'accounts'

from .views import LoginView, SignUpView, UpdateView, logout_view
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('update/<int:pk>/', UpdateView.as_view(), name='update'),
    path('logout/', logout_view, name='logout'),
]

shop/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView

app_name = 'shop'

urlpatterns = [
    path('', index, name='home'),
    path('about/', TemplateView.as_view(template_name='shop/about.html'), name='about'),
    path('products/', ProductListView.as_view(), name='products'),
    path('vintages/', ProductVintageListView.as_view(), name='vintages_list'),
    path('vintages/<int:pk>/', ProductVintageListView.as_view(), name='vintages'), # pk = product id
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('productvintage/<int:pk>/', ProductVintageDetailView.as_view(), name='vintage_detail'), # pk = vintage id
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('productvintages/update/<int:pk>/', ProductUpdateView.as_view(), name='vintage_update'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('productvintages/create/', ProductCreateView.as_view(), name='vintage_create'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('productvintages/delete/<int:pk>/', ProductDeleteView.as_view(), name='vintage_delete'),
    path('products/order/<int:pk>/', CustomerOrderView.as_view(), name='customer_order'),
    path('products/order/availability/<int:pk>/', vintage_availability, name='vintage_availability'),
    path('customers/', CustomerListView.as_view(), name='customers'),
    path('orders/', OrderListView.as_view(), name='orders'),
    path('purchases/', PurchasesListView.as_view(), name='purchases'),
    path('customer/orders/update/<int:pk>/', update_order, name='update_customer_order'),
    path('customer/orders/purchase/', purchase_orders, name='purchase_customer_orders'),
    path('customer/purchase/payment/<int:pk>', PayView.as_view(), name='payment'),
    path('customer/orders/delete/<int:pk>/', delete_customer_order, name='customer_delete_order'),
    path('orders/update/<int:pk>/', StaffOrderView.as_view(), name='update_order'),
    path('purchases/update/<int:pk>/', PurchaseUpdateStateView.as_view(), name='update_purchase'),
    path('cart/', CartView.as_view(), name='cart'),
]

shop/models.py
from django.db import models
from .choices import STATE_CHOICES, ORDER_CHOICES
from django.db.models import Sum

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.name

class ProductVintage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    vintage = models.IntegerField()
    vintage_description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    stock = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.product} - {self.vintage}"
    
    @property
    def available_stock(self):
        # Calculate the total quantity of reserved orders with a state lower than three
        reserved_quantity = ReservedOrder.objects.filter(product=self, state__lt=2).aggregate(Sum('quantity'))['quantity__sum'] or 0
        # Subtract the reserved quantity from the available stock
        return self.stock - reserved_quantity

class ReservedOrder(models.Model):
    # product is actually the vintage!
    product = models.ForeignKey(ProductVintage, on_delete=models.SET_NULL, null=True, default=None, related_name='vintages')
    quantity = models.PositiveIntegerField()
    customer = models.ForeignKey('accounts.Customer', on_delete=models.SET_NULL, null=True, default=None, related_name='userorders')
    ordered_at = models.DateTimeField(auto_now_add=True)
    state = models.IntegerField(choices=ORDER_CHOICES, default=0, null=True, blank=True)

    def __str__(self):
        return f"{self.product}, Amount: {self.quantity}, Price: {self.product.price} €, Total: {self.product.price * self.quantity} €"
    

class Purchase(models.Model):
    orders = models.ManyToManyField(ReservedOrder)
    total_price = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)
    purchased_at = models.DateTimeField(auto_now_add=True)
    state = models.IntegerField(choices=STATE_CHOICES, default=0, null=True, blank=True)

shop/forms.py
from .models import Product, ProductVintage, ReservedOrder, Purchase
from django import forms

from .choices import STATE_CHOICES, ORDER_CHOICES

class CustomerOrderForm(forms.ModelForm):
    '''Form for customers to place an order'''
    class Meta:
        model = ReservedOrder
        fields = ['product', 'quantity']

    def __init__(self, *args, **kwargs):
        super(CustomerOrderForm, self).__init__(*args, **kwargs)


class CustomerOrderDeleteForm(forms.ModelForm):
    '''Form for customers to delete their reserved order'''
    class Meta:
        model = ReservedOrder
        fields = []

    def __init__(self, *args, **kwargs):
        super(CustomerOrderDeleteForm, self).__init__(*args, **kwargs)

class StaffOrderForm(forms.ModelForm):
    '''Form for staff to update the state of an order'''
    class Meta:
        model = ReservedOrder
        fields = ['state']
    
    def __init__(self, *args, **kwargs):
        super(StaffOrderForm, self).__init__(*args, **kwargs)
        self.fields['state'].widget.attrs['class'] = 'form-select'
        self.fields['state'].choices = ORDER_CHOICES

        
class StaffPurchaseForm(forms.ModelForm):
    '''Form for staff to update the state of a purchase'''
    class Meta:
        model = Purchase
        fields = ['state']
    
    def __init__(self, *args, **kwargs):
        super(StaffPurchaseForm, self).__init__(*args, **kwargs)
        self.fields['state'].widget.attrs['class'] = 'form-select'
        self.fields['state'].choices = STATE_CHOICES
        

class ProductForm(forms.ModelForm):
    '''Form for staff to create and update products'''
    class Meta:
        model = Product
        fields = ['name', 'description']


class ProductVintageForm(forms.ModelForm):
    '''Form for staff to create and update products'''
    class Meta:
        model = ProductVintage
        fields = ['product', 'vintage', 'vintage_description', 'price', 'stock']

class CustomerPaymentForm(forms.ModelForm):
    '''Form for customers to simulate payment of a purchase'''
    class Meta:
        model = Purchase
        fields = ['state']

    def __init__(self, *args, **kwargs):
        super(CustomerPaymentForm, self).__init__(*args, **kwargs)
        self.fields['state'].widget.attrs['class'] = 'form-select'
        self.fields['state'].choices = STATE_CHOICES

shop/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Product, ProductVintage, ReservedOrder, Purchase
from accounts.models import Customer
from .forms import *
from django.urls import reverse_lazy
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.db.models import Q, F, FloatField, ExpressionWrapper, Value
from django.db import transaction
from datetime import datetime
from django.http import JsonResponse
import json
from collections import defaultdict

# Create your views here.

def index(request):
    return render(request, 'shop/index.html')

class ProductListView(ListView):
    '''View for listing all products'''
    model = Product
    template_name = 'shop/product_list.html'
    context_object_name = 'products'

class ProductVintageListView(ListView):
    '''View for listing all vintages of a product'''
    model = ProductVintage
    template_name = 'shop/product_vintage_list.html'
    context_object_name = 'vintages'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "pk" in self.kwargs:
            context['product'] = Product.objects.get(id=self.kwargs['pk'])
        else:
            self.template_name = 'shop/vintages_list.html'
        return context
    
    def get_queryset(self):
        if "pk" in self.kwargs:
            return ProductVintage.objects.filter(product=self.kwargs['pk'])
        else:
            vintages = ProductVintage.objects.all().order_by('vintage')
            # Grouping by vintage
            vintages_grouped = defaultdict(list)
            for vintage in vintages:
                vintages_grouped[vintage.vintage].append(vintage)
            vintages = dict(vintages_grouped)
            return vintages

class ProductDetailView(DetailView):
    '''View for displaying a single product'''
    model = Product
    template_name = 'shop/product_detail.html'
    context_object_name = 'product'

class ProductVintageDetailView(DetailView):
    '''View for displaying a single vintage of a product'''
    model = ProductVintage
    template_name = 'shop/product_vintage_detail.html'
    context_object_name = 'vintage'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['vintage'] = ProductVintage.objects.get(id=self.kwargs['pk'])
        return context


class ProductCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    '''View for staff to create products'''
    model = Product
    form_class = ProductForm
    template_name = 'shop/product_create.html'
    success_url = reverse_lazy('shop:products')

    def get(self, request, *args, **kwargs):
        self.set_vintage_form(request)
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.set_vintage_form(request)        
        post = super().post(request, *args, **kwargs)
        return post
    
    def set_vintage_form(self, request):
        if "vintage" in request.path:
            self.template_name = "shop/product_vintage_create.html"
            self.form_class = ProductVintageForm
            self.model = ProductVintage
            product_id = request.GET.get('product')
            if product_id:
                self.initial = {'product': product_id}
    
    def form_valid(self, form):
        # Save the form and get the saved object
        saved_object = form.save()
        
        if "vintage" in self.request.path:
            # Redirect to the vintages view with the saved object's ID
            return redirect('shop:vintages', pk=saved_object.product.id)
        
        return super().form_valid(form)


    def test_func(self):
        # Only staff members can create products
        return self.request.user.is_staff


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    '''View for staff to update products'''
    model = Product
    form_class = ProductForm
    template_name = 'shop/product_update.html'
    success_url = reverse_lazy('shop:products')

    def set_vintage_form(self, request):
        if "vintage" in request.path:
            self.template_name = "shop/product_vintage_update.html"
            self.form_class = ProductVintageForm
            self.model = ProductVintage
            self.success_url = reverse_lazy('shop:vintages', kwargs={'pk': self.get_object().product.id})

    def post(self, request, *args, **kwargs):
        self.set_vintage_form(request)
        return super().post(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.set_vintage_form(request)
        return super().get(request, *args, **kwargs)

    def test_func(self):
        # Only staff members can update products
        return self.request.user.is_staff

class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    '''View for staff to delete products'''
    model = Product
    template_name = 'shop/product_delete.html'
    success_url = reverse_lazy('shop:products')

    def set_vintage_form(self, request):
        if "vintage" in request.path:
            self.template_name = "shop/product_vintage_delete.html"
            self.model = ProductVintage
            self.success_url = reverse_lazy('shop:vintages', kwargs={'pk': self.get_object().product.id})

    def get(self, request, *args, **kwargs):
        self.set_vintage_form(request)
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.set_vintage_form(request)
        return super().post(request, *args, **kwargs)

    def test_func(self):
        # Only staff members can delete products
        return self.request.user.is_staff
    

class CustomerListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    '''View for listing all customers'''
    model = ReservedOrder
    template_name = 'shop/customers.html'
    
    def test_func(self):
        # Only staff members can view customers
        return self.request.user.is_staff
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # get the search parameter "?=search"
        search = self.request.GET.get('search')
        if search:
            context['customers'] = Customer.objects.filter(Q(username__icontains=search) | Q(first_name__icontains=search) | Q(last_name__icontains=search))
        else:
            context['customers'] = Customer.objects.all()
        return context
    
class CustomerOrderView(CreateView):
    '''View for customers to place an order'''
    model = ReservedOrder
    form_class = CustomerOrderForm
    template_name = 'shop/customer_order.html'
    success_url = reverse_lazy('shop:products')
    
    def form_valid(self, form):
        form.instance.customer = self.request.user
        form = super().form_valid(form)
        return form
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.all().values('id', 'name')
        context['product'] = Product.objects.get(pk=self.kwargs['pk'])
        form = context['form']
        choices = form.fields['product']
        choices.queryset = ProductVintage.objects.filter(product_id=self.kwargs['pk'])
        choice = self.request.GET.get('vintage')
        if not choice:
            choice = choices.queryset[0].id
        vintage = ProductVintage.objects.get(pk=choice)
        context['price'] = vintage.price
        form.fields['product'].label = 'Vintage'
        form.fields['product'].initial = choice
        form.fields['quantity'].widget.attrs['max'] = vintage.available_stock
        form.fields['quantity'].widget.attrs['min'] = 1
        form.fields['quantity'].initial = 1
        return context

def vintage_availability(request, *args, **kwargs):
    '''function to request the availability of a vintage'''
    if request.method == 'GET':
        pk = kwargs['pk']
        if pk is None:
            return JsonResponse({'error': 'pk parameter is missing'}, status=400)
        availability = get_object_or_404(ProductVintage, pk=pk)
        return JsonResponse({'stock': availability.available_stock, 'price': availability.price})
    else:
        return JsonResponse({'error': 'GET request required'}, status=400)

class StaffOrderView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    '''View for staff to update the state of an order'''
    model = ReservedOrder
    form_class = StaffOrderForm
    template_name = 'shop/order_update.html'
    success_url = reverse_lazy('shop:orders')

    def test_func(self):
        # Only staff members can update orders
        return self.request.user.is_staff
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order'] = ReservedOrder.objects.get(pk=self.kwargs['pk'])
        context['form']['state'].initial = context['order'].state
        context['form'].fields['state'].choices = ORDER_CHOICES[:2]
        return context


class OrderListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    '''View for listing all orders'''
    model = ReservedOrder
    template_name = 'shop/order_list.html'
    
    def test_func(self):
        # Only staff members can view orders
        return self.request.user.is_staff
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['customers'] = Customer.objects.all().values('id', 'username', 'first_name', 'last_name')
        context['products'] = Product.objects.all().values('id', 'name')
        orders = ReservedOrder.objects.all()        
        dates = []

shop/templates/base.html
{% load static %}
{% load custom_filters %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>d-Wine</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- {% block extra_css %}{% endblock %} -->
    <style>
        body {
            background-image: url("{% static background_image_url %}");
            background-size: cover;
            background-attachment: fixed;
            background-repeat: no-repeat;
        }
    </style>
</head>
<header>
    <nav class="navbar" style="text-align: center;">
        {% if user.is_authenticated %}
            <ul>
                <li class="btn btn-outline-light"><a href="{% url 'accounts:update' user.id %}">Welcome, {{user.username}}</a></li>
                <li class="btn btn-outline-light"><a href="{% url 'logout' %}">logout</a></li>
            </ul>
            <ul>
                {% if user.is_staff %}
                <li class="btn btn-outline-light"><a href="{% url 'shop:product_create' %}">Add Product</a></li>
                <li class= "btn btn-outline-light"><a href="{% url 'shop:customers' %}">Customers</a></li>
                <li class= "btn btn-outline-light"><a href="{% url 'shop:orders' %}">Orders</a></li>
                <li class= "btn btn-outline-light"><a href="{% url 'shop:purchases' %}">Purchases</a></li>
                {% else %}
                {% with user.userorders.all as userorders %}
                    {% with userorders|state_filtered|length as pending_badge %}
                        {% with userorders|state_filtered:1|length as whishing_badge %}
                            {% with userorders|unpayed as payment_badge %}
                                <li class="btn btn-outline-light" style="position: relative;">
                                    <a href="{% url 'shop:cart' %}" style="display: inline-block;">cart
                                        {% if pending_badge %} <span class="badge badge-success" style="position: absolute; top: -12px; right: -8px;">
                                            {{ pending_badge }}</span>
                                        {% endif %}
                                        {% if whishing_badge %} <span class="badge badge-warning" style="position: absolute; top: 9px; right: -8px;">
                                            {{ whishing_badge }}</span>
                                        {% endif %}
                                        {% if payment_badge %} <span class="badge badge-danger" style="position: absolute; top: 30px; right: -8px;">
                                            {{ payment_badge }}</span>
                                        {% endif %}
                                    </a>
                                </li>
                            {% endwith %}
                        {% endwith %}
                    {% endwith %}
                {% endwith %}
                {% endif %}
            </ul>
        {% else %}
        <ul>
            <li class="btn btn-outline-light"><a href="{% url 'accounts:login' %}">login</a></li>
            <li class="btn btn-outline-light"><a href="{% url 'accounts:signup' %}">signup</a></li>
        </ul>
        {% endif %}
        <h1 style="margin: 20px;"><a href="{% url 'shop:home' %}">d-Wine</a></h1>
        <ul>
            <li class="btn btn-outline-light"><a href="{% url 'shop:about' %}">About</a></li>
            <li class="btn btn-outline-light"><a href="{% url 'shop:products' %}">Products</a></li>
            <li class="btn btn-outline-light"><a href="{% url 'shop:vintages_list' %}">Vintages</a></li>
        </ul>
    </nav>
</header>
<body>
    <div style="position: sticky; display: flex; flex-direction: column; margin: 10px; align-items: end; top:0; z-index: 1000;">
        <div style="width: 180px; -webkit-backdrop-filter: blur(3px); backdrop-filter: blur(3px); padding: 10px; border-radius: 10px;">
            <label for="font-selector">Change font:</label>
            <select id="font-selector">
            <option value="default">Celtic</option>
            <option value="font2">Typewriter</option>
            <option value="font1">Minecraft</option>
            </select>
        </div>
    </div>
    <section>
        {% block content %}{% endblock %}
    </section>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const fontSelector = document.getElementById('font-selector');

            // Load the saved font from local storage
            const savedFont = localStorage.getItem('selectedFont');
            if (savedFont) {
                document.body.classList.add(savedFont);
                fontSelector.value = savedFont;
            }
            
            fontSelector.addEventListener('change', function() {
                // Remove any previously applied font class
                document.body.classList.remove('font1', 'font2');

                // Get the selected font
                const selectedFont = fontSelector.value;

                // Apply the selected font class to the body
                if (selectedFont !== 'default') {
                    document.body.classList.add(selectedFont);
                }

                // Save the selected font to local storage
                localStorage.setItem('selectedFont', selectedFont);
            });
        });
    </script>
</body>
</html>