WeinhandelDjP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('accounts/', include('accounts.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
]

shop/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView

app_name = 'shop'

urlpatterns = [
    path('', index, name='home'),
    path('about/', TemplateView.as_view(template_name='shop/about.html'), name='about'),
    path('products/', ProductListView.as_view(), name='products'),
    path('vintages/', ProductVintageListView.as_view(), name='vintages_list'),
    path('vintages/<int:pk>/', ProductVintageListView.as_view(), name='vintages'), # pk = product id
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('productvintage/<int:pk>/', ProductVintageDetailView.as_view(), name='vintage_detail'), # pk = vintage id
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('productvintages/update/<int:pk>/', ProductUpdateView.as_view(), name='vintage_update'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('productvintages/create/', ProductCreateView.as_view(), name='vintage_create'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('productvintages/delete/<int:pk>/', ProductDeleteView.as_view(), name='vintage_delete'),
    path('products/order/<int:pk>/', CustomerOrderView.as_view(), name='customer_order'),
    path('products/order/availability/<int:pk>/', vintage_availability, name='vintage_availability'),
    path('customers/', CustomerListView.as_view(), name='customers'),
    path('orders/', OrderListView.as_view(), name='orders'),
    path('purchases/', PurchasesListView.as_view(), name='purchases'),
    path('customer/orders/update/<int:pk>/', update_order, name='update_customer_order'),
    path('customer/orders/purchase/', purchase_orders, name='purchase_customer_orders'),
    path('customer/purchase/payment/<int:pk>', PayView.as_view(), name='payment'),
    path('customer/orders/delete/<int:pk>/', delete_customer_order, name='customer_delete_order'),
    path('orders/update/<int:pk>/', StaffOrderView.as_view(), name='update_order'),
    path('purchases/update/<int:pk>/', PurchaseUpdateStateView.as_view(), name='update_purchase'),
    path('cart/', CartView.as_view(), name='cart'),
]

shop/models.py
from django.db import models
from .choices import STATE_CHOICES, ORDER_CHOICES
from django.db.models import Sum

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.name

class ProductVintage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    vintage = models.IntegerField()
    vintage_description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    stock = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.product} - {self.vintage}"
    
    @property
    def available_stock(self):
        # Calculate the total quantity of reserved orders with a state lower than three
        reserved_quantity = ReservedOrder.objects.filter(product=self, state__lt=2).aggregate(Sum('quantity'))['quantity__sum'] or 0
        # Subtract the reserved quantity from the available stock
        return self.stock - reserved_quantity

class ReservedOrder(models.Model):
    # product is actually the vintage!
    product = models.ForeignKey(ProductVintage, on_delete=models.SET_NULL, null=True, default=None, related_name='vintages')
    quantity = models.PositiveIntegerField()
    customer = models.ForeignKey('accounts.Customer', on_delete=models.SET_NULL, null=True, default=None, related_name='userorders')
    ordered_at = models.DateTimeField(auto_now_add=True)
    state = models.IntegerField(choices=ORDER_CHOICES, default=0, null=True, blank=True)

    def __str__(self):
        return f"{self.product}, Amount: {self.quantity}, Price: {self.product.price} €, Total: {self.product.price * self.quantity} €"
    

class Purchase(models.Model):
    orders = models.ManyToManyField(ReservedOrder)
    total_price = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)
    purchased_at = models.DateTimeField(auto_now_add=True)
    state = models.IntegerField(choices=STATE_CHOICES, default=0, null=True, blank=True)

shop/forms.py
from .models import Product, ProductVintage, ReservedOrder, Purchase
from django import forms

from .choices import STATE_CHOICES, ORDER_CHOICES

class CustomerOrderForm(forms.ModelForm):
    '''Form for customers to place an order'''
    class Meta:
        model = ReservedOrder
        fields = ['product', 'quantity']

    def __init__(self, *args, **kwargs):
        super(CustomerOrderForm, self).__init__(*args, **kwargs)


class CustomerOrderDeleteForm(forms.ModelForm):
    '''Form for customers to delete their reserved order'''
    class Meta:
        model = ReservedOrder
        fields = []

    def __init__(self, *args, **kwargs):
        super(CustomerOrderDeleteForm, self).__init__(*args, **kwargs)

class StaffOrderForm(forms.ModelForm):
    '''Form for staff to update the state of an order'''
    class Meta:
        model = ReservedOrder
        fields = ['state']
    
    def __init__(self, *args, **kwargs):
        super(StaffOrderForm, self).__init__(*args, **kwargs)
        self.fields['state'].widget.attrs['class'] = 'form-select'
        self.fields['state'].choices = ORDER_CHOICES

        
class StaffPurchaseForm(forms.ModelForm):
    '''Form for staff to update the state of a purchase'''
    class Meta:
        model = Purchase
        fields = ['state']
    
    def __init__(self, *args, **kwargs):
        super(StaffPurchaseForm, self).__init__(*args, **kwargs)
        self.fields['state'].widget.attrs['class'] = 'form-select'
        self.fields['state'].choices = STATE_CHOICES
        

class ProductForm(forms.ModelForm):
    '''Form for staff to create and update products'''
    class Meta:
        model = Product
        fields = ['name', 'description']


class ProductVintageForm(forms.ModelForm):
    '''Form for staff to create and update products'''
    class Meta:
        model = ProductVintage
        fields = ['product', 'vintage', 'vintage_description', 'price', 'stock']

class CustomerPaymentForm(forms.ModelForm):
    '''Form for customers to simulate payment of a purchase'''
    class Meta:
        model = Purchase
        fields = ['state']

    def __init__(self, *args, **kwargs):
        super(CustomerPaymentForm, self).__init__(*args, **kwargs)
        self.fields['state'].widget.attrs['class'] = 'form-select'
        self.fields['state'].choices = STATE_CHOICES

shop/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Product, ProductVintage, ReservedOrder, Purchase
from accounts.models import Customer
from .forms import *
from django.urls import reverse_lazy
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.db.models import Q, F, FloatField, ExpressionWrapper, Value
from django.db import transaction
from datetime import datetime
from django.http import JsonResponse
import json
from collections import defaultdict

# Create your views here.

def index(request):
    return render(request, 'shop/index.html')

class ProductListView(ListView):
    '''View for listing all products'''
    model = Product
    template_name = 'shop/product_list.html'
    context_object_name = 'products'

class ProductVintageListView(ListView):
    '''View for listing all vintages of a product'''
    model = ProductVintage
    template_name = 'shop/product_vintage_list.html'
    context_object_name = 'vintages'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "pk" in self.kwargs:
            context['product'] = Product.objects.get(id=self.kwargs['pk'])
        else:
            self.template_name = 'shop/vintages_list.html'
        return context
    
    def get_queryset(self):
        if "pk" in self.kwargs:
            return ProductVintage.objects.filter(product=self.kwargs['pk'])
        else:
            vintages = ProductVintage.objects.all().order_by('vintage')
            # Grouping by vintage
            vintages_grouped = defaultdict(list)
            for vintage in vintages:
                vintages_grouped[vintage.vintage].append(vintage)
            vintages = dict(vintages_grouped)
            return vintages

class ProductDetailView(DetailView):
    '''View for displaying a single product'''
    model = Product
    template_name = 'shop/product_detail.html'
    context_object_name = 'product'

class ProductVintageDetailView(DetailView):
    '''View for displaying a single vintage of a product'''
    model = ProductVintage
    template_name = 'shop/product_vintage_detail.html'
    context_object_name = 'vintage'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['vintage'] = ProductVintage.objects.get(id=self.kwargs['pk'])
        return context


class ProductCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    '''View for staff to create products'''
    model = Product
    form_class = ProductForm
    template_name = 'shop/product_create.html'
    success_url = reverse_lazy('shop:products')

    def get(self, request, *args, **kwargs):
        self.set_vintage_form(request)
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.set_vintage_form(request)        
        post = super().post(request, *args, **kwargs)
        return post
    
    def set_vintage_form(self, request):
        if "vintage" in request.path:
            self.template_name = "shop/product_vintage_create.html"
            self.form_class = ProductVintageForm
            self.model = ProductVintage
            product_id = request.GET.get('product')
            if product_id:
                self.initial = {'product': product_id}
    
    def form_valid(self, form):
        # Save the form and get the saved object
        saved_object = form.save()
        
        if "vintage" in self.request.path:
            # Redirect to the vintages view with the saved object's ID
            return redirect('shop:vintages', pk=saved_object.product.id)
        
        return super().form_valid(form)


    def test_func(self):
        # Only staff members can create products
        return self.request.user.is_staff


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    '''View for staff to update products'''
    model = Product
    form_class = ProductForm
    template_name = 'shop/product_update.html'
    success_url = reverse_lazy('shop:products')

    def set_vintage_form(self, request):
        if "vintage" in request.path:
            self.template_name = "shop/product_vintage_update.html"
            self.form_class = ProductVintageForm
            self.model = ProductVintage
            self.success_url = reverse_lazy('shop:vintages', kwargs={'pk': self.get_object().product.id})

    def post(self, request, *args, **kwargs):
        self.set_vintage_form(request)
        return super().post(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.set_vintage_form(request)
        return super().get(request, *args, **kwargs)

    def test_func(self):
        # Only staff members can update products
        return self.request.user.is_staff

class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    '''View for staff to delete products'''
    model = Product
    template_name = 'shop/product_delete.html'
    success_url = reverse_lazy('shop:products')

    def set_vintage_form(self, request):
        if "vintage" in request.path:
            self.template_name = "shop/product_vintage_delete.html"
            self.model = ProductVintage
            self.success_url = reverse_lazy('shop:vintages', kwargs={'pk': self.get_object().product.id})

    def get(self, request, *args, **kwargs):
        self.set_vintage_form(request)
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.set_vintage_form(request)
        return super().post(request, *args, **kwargs)

    def test_func(self):
        # Only staff members can delete products
        return self.request.user.is_staff
    

class CustomerListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    '''View for listing all customers'''
    model = ReservedOrder
    template_name = 'shop/customers.html'
    
    def test_func(self):
        # Only staff members can view customers
        return self.request.user.is_staff
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # get the search parameter "?=search"
        search = self.request.GET.get('search')
        if search:
            context['customers'] = Customer.objects.filter(Q(username__icontains=search) | Q(first_name__icontains=search) | Q(last_name__icontains=search))
        else:
            context['customers'] = Customer.objects.all()
        return context
    
class CustomerOrderView(CreateView):
    '''View for customers to place an order'''
    model = ReservedOrder
    form_class = CustomerOrderForm
    template_name = 'shop/customer_order.html'
    success_url = reverse_lazy('shop:products')
    
    def form_valid(self, form):
        form.instance.customer = self.request.user
        form = super().form_valid(form)
        return form
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.all().values('id', 'name')
        context['product'] = Product.objects.get(pk=self.kwargs['pk'])
        form = context['form']
        choices = form.fields['product']
        choices.queryset = ProductVintage.objects.filter(product_id=self.kwargs['pk'])
        choice = self.request.GET.get('vintage')
        if not choice:
            choice = choices.queryset[0].id
        vintage = ProductVintage.objects.get(pk=choice)
        context['price'] = vintage.price
        form.fields['product'].label = 'Vintage'
        form.fields['product'].initial = choice
        form.fields['quantity'].widget.attrs['max'] = vintage.available_stock
        form.fields['quantity'].widget.attrs['min'] = 1
        form.fields['quantity'].initial = 1
        return context

def vintage_availability(request, *args, **kwargs):
    '''function to request the availability of a vintage'''
    if request.method == 'GET':
        pk = kwargs['pk']
        if pk is None:
            return JsonResponse({'error': 'pk parameter is missing'}, status=400)
        availability = get_object_or_404(ProductVintage, pk=pk)
        return JsonResponse({'stock': availability.available_stock, 'price': availability.price})
    else:
        return JsonResponse({'error': 'GET request required'}, status=400)

class StaffOrderView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    '''View for staff to update the state of an order'''
    model = ReservedOrder
    form_class = StaffOrderForm
    template_name = 'shop/order_update.html'
    success_url = reverse_lazy('shop:orders')

    def test_func(self):
        # Only staff members can update orders
        return self.request.user.is_staff
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order'] = ReservedOrder.objects.get(pk=self.kwargs['pk'])
        context['form']['state'].initial = context['order'].state
        context['form'].fields['state'].choices = ORDER_CHOICES[:2]
        return context


class OrderListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    '''View for listing all orders'''
    model = ReservedOrder
    template_name = 'shop/order_list.html'
    
    def test_func(self):
        # Only staff members can view orders
        return self.request.user.is_staff
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['customers'] = Customer.objects.all().values('id', 'username', 'first_name', 'last_name')
        context['products'] = Product.objects.all().values('id', 'name')
        orders = ReservedOrder.objects.all()        
        dates = []

shop/templates/shop/customer_order.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div style="max-height: 75vh; overflow-y: auto;">
    <h3>Place your order for {{ product.name }}:</h3>
    <p>({{ product.description }})</p>
    <select name="product_select" id="product_id">
        <option value="-1">-- product--</option>
        {% for product in products %}
            <option value="{{ product.id }}">{{ product.name }}</option>
        {% endfor %}
    </select>
    <form method="post" action="{% url 'shop:customer_order' product.id %}" id="new-form" class="topspace">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <h3 id="id_total">price: {{ price }} €</h3>
        <button class="btn btn-success topspace" method="post" id="submitMess" type="submit">Order</button>
    </form>
</div>
<script>
    var price = {{ price }};
    quantity = document.getElementById("id_quantity");
    vintage_product = document.getElementById("id_product");
    vine_product = document.getElementById("product_id")
    vine_product.value = {{ product.id }};
    vine_product.addEventListener("change", function(event) {
        // update the form with the selected product
        vine_product_id = event.target.value;
        if (vine_product_id == -1) {
            return;
        }
        url = "{% url 'shop:customer_order' 0 %}".replace('0', vine_product_id);
        window.location.href = url
    })
    vintage_product.addEventListener("change", function(event) {
        // update the price and quantity
        vintage_product_id = event.target.value;
        if (vintage_product_id == "") {
            return;
        }
        url = "{% url 'shop:vintage_availability' 0 %}".replace('0', vintage_product_id);
        fetch(url)
            .then(response => response.json())
            .then(data => {
                quantity.max = data.available_stock;
                price = data.price;
                var total = quantity.value * price;
                document.getElementById("id_total").innerText = 'total price: ' + total + ' €';
            });
    });
    quantity.addEventListener("change", function() {
        var total = quantity.value * price;
        document.getElementById("id_total").innerText = 'total price: ' + total + ' €';
    });
</script>
{% endblock %}

shop/templates/shop/customers.html
{% extends 'base.html' %}
{% load custom_filters %}
{% load crispy_forms_tags %}
{% block content %}
<h3>Our customers:</h3>
<input type="search" placeholder="search filter" id="search_input">
<ol>
    {% for customer in customers %}
        <li>
            <h5>{{ customer.username }}</h5>
            {% if customer.first_name and customer.last_name %}
                <p><em>Full name:</em> {{ customer.first_name }} {{ customer.last_name }}</p>
            {% endif %}
            {% with customer.userorders.all as orders %}
                {% if not orders %}
                    <p><em>No orders yet.</em></p>
                {% else %}
                    <p><a href="{% url 'shop:orders' %}?customer={{customer.id}}"><em>total Orders:</em> {{ orders.count }}</a><br>
                    {% with orders|state_filtered as pendings %}
                        {% if pendings %}
                            <a href="{% url 'shop:orders' %}?state=0&customer={{customer.id}}"><em>pending Orders:</em> {{ pendings|length }}</a><br>
                        {% endif %}
                    {% endwith %}
                    {% with orders|state_filtered:1 as wishlists %}
                        {% if wishlists %}
                            <a href="{% url 'shop:orders' %}?state=1&customer={{customer.id}}"><em>wishlist Orders:</em> {{wishlists|length}}</a><br>
                        {% endif %}
                    {% endwith %}
                    {% with orders|state_filtered:2 as purchases %}
                        {% if purchases %}
                            <a href="{% url 'shop:orders' %}?state=2&customer={{customer.id}}"><em>purchased Orders:</em> {{purchases|length}}</a><br>
                        {% endif %}
                    {% endwith %}
                    </p>
                {% endif %}
            {% endwith %}
            <a class="btn btn-outline-light" href= "mailto: {customer.email}">Contact</a>
        </li>
    {% endfor %}
</ol>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        var search_input = document.getElementById("search_input");
        // if there is a search parameter in url, set the search input value to it
        search_val = window.location.search.split("?search=")[1];
        if (search_val) {
            search_input.value = search_val;
            // set search_input active
            search_input.focus();
        }
        // if the search input changes, reload the page with the new search
        search_input.addEventListener("input", function() {
            var search = search_input.value.toLowerCase();
            window.location.href = "{% url 'shop:customers' %}?search=" + search;
        });
    });
</script>
{% endblock %}

shop/templates/shop/product_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div style="max-height: 75vh; overflow-y: auto;">
    <form method="post" action="{% url 'shop:product_create' %}" id="new-form">
    <h3>Add a new product's data here:</h3>
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-outline-light" method="post" id="submitMess" type="submit">Create</button>
</form>
<a class="btn btn-outline-light" href="{% url 'shop:vintage_create' %}" style="margin-top: 10px;">Or create a product's new vintage here</a>
</div>
{% endblock %}

shop/templates/shop/product_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div style="max-height: 75vh; overflow-y: auto;">
    <form method="post" action="{% url 'shop:product_delete' product.id %}">
    <h3>Sure you want to delete {{ product.name }}?!:</h3>
    <p><strong><em>This operation cannot be undone!!!</em></strong></p>
    {% csrf_token %}
    <button class="btn btn-outline-danger" method="post" id="submitMess" type="submit">Delete irrevocably</button>
</form>
</div>
{% endblock %}

shop/templates/shop/product_detail.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ product.name }}</h1>
    <h3>Description:</h3>
    <p>{{ product.description }}</p>
    {% with product.productvintage_set.all as vintages %}
        <h3>Vintages: 
            {% for vintage in vintages %}
                <a class="btn btn btn-outline-light" href="{% url 'shop:vintage_detail' vintage.id %}">{{ vintage.vintage }}</a>
            {% endfor %}
        </h3>
        {% if user.is_staff and vintages %}
            <a class="btn btn btn-outline-light" style="margin: 20px;" href="{% url 'shop:product_update' product.id %}">Update</a>
            <a class="btn btn btn-outline-warning" style="margin: 20px;" href="{% url 'shop:product_delete' product.id %}">Delete</a>
        {% elif user.is_authenticated and vintages %}
            <td><a class="btn btn btn-success topspace" href="{% url 'shop:customer_order' product.id %}">Order</a></td>
        {% elif not vintages %}
            <p>No vintages available.</p>
        {% endif %}
        {% if user.is_staff %}
            <a class="btn btn-outline-light" style="margin: 20px; width: 80%;" href="{% url 'shop:vintage_create' %}?product={{ product.id }}">Add a new Vintage</a>
        {% endif %}
    {% endwith %}
{% endblock %}

shop/templates/shop/product_list.html
{% extends 'base.html' %}
{% block content %}
    <h1>our d-Wines:</h1>
    <div style="overflow: scroll; height: 63vh; margin-top: 20px;">
        <table id="scrollable-table" style="overflow-x:auto;">
            <thead>
                <tr>
                    <th>Name:</th>
                    <th>Description:</th>
                    <th>Vintages:</th>
                    {% if user.is_authenticated %}
                        {% if user.is_staff %}
                            <th>Update:</th>
                            <th>Delete:</th>
                        {% else %}
                            <th>Buy:</th>
                        {% endif %}
                    {% endif %}
                </tr>
            </thead>
            {% for product in products %}
                <tr>
                    {% with product.productvintage_set.all as vintages %}
                        <td><a class="btn btn btn-outline-light" href="{% url 'shop:product_detail' product.id %}" style="padding:5px; white-space: normal;" >{{ product.name }}</a></td>
                        <td title="{{ product.description }}">{{ product.description|truncatewords:15 }}</td>
                            <td>
                                <div style="overflow: scroll;">
                                    {% if vintages %}
                                        <a class="btn btn btn-outline-light" href="{% url 'shop:vintages' product.id %}">
                                            {% for vintage in vintages %}
                                                {{ vintage.vintage }}{% if not forloop.last %}, {% endif %}<br>
                                            {% endfor %}
                                        </a>
                                    {% else %}
                                        <p>No vintages available.</p>
                                    {% endif %}
                                    
                                    {% if user.is_staff %}
                                        <a href="{% url 'shop:vintage_create' %}?product={{ product.id }}" style="margin-top: 10px;"><em>add new</em></a>
                                    {% endif %}
                                </div>
                            </td>
                        {% if user.is_staff %}
                            <td><a class="btn btn btn-outline-light" href="{% url 'shop:product_update' product.id %}">Update</a></td>
                            <td><a class="btn btn btn-outline-warning" href="{% url 'shop:product_delete' product.id %}">Delete</a></td>
                        {% elif user.is_authenticated and vintages %}
                            <td><a class="btn btn btn-success" href="{% url 'shop:customer_order' product.id %}">Order</a></td>
                        {% endif %}
                    {% endwith %}
                </tr>
            {% endfor %}
        </table>
    </div>
    {% if user.is_staff %}
        <tr>
            <td colspan="4">
                <a class="btn btn-outline-light" style="margin: 20px; width: 80%;" href="{% url 'shop:product_create' %}">Add a new Product</a>
            </td>
        </tr>
    {% endif %}
{% endblock %}

shop/templates/shop/product_vintage_detail.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block content %}
    <h1>{{ vintage.product.name }} {{vintage.vintage}}</h1>
    <p>({{ vintage.product.description }})</h3>
    <h3>Vintage Description:</h3>
    <p>{{ vintage.vintage_description }}</p>
    <h3>Price: {{ vintage.price }} €</h3>
    {% with vintage.stock|difference:vintage.available_stock as avail_diff %}
    <h3>Available: {{ vintage.available_stock }}{% if avail_diff %}<em> ({{ avail_diff }} reserved)</em>{% endif %}</h3>
        </td>
    {% endwith %}
    {% if user.is_staff %}
        <a class="btn btn btn-outline-light" style="margin: 20px;" href="{% url 'shop:vintage_update' vintage.id %}">Update</a>
        <a class="btn btn btn-outline-warning" style="margin: 20px;" href="{% url 'shop:vintage_delete' vintage.id %}">Delete</a>
    {% elif user.is_authenticated %}
        <td><a class="btn btn btn-success topspace" href="{% url 'shop:customer_order' vintage.product.id %}?vintage={{vintage.id}}">Order</a></td>
    {% endif %}
{% endblock %}

shop/templates/shop/product_vintage_list.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block content %}
    <h1>our vintages for {{ product.name }}:</h1>
    <p>({{ product.description }})</p>
    <div style="overflow: scroll; height: 57vh; margin-top: 20px;">
        <table id="scrollable-table" style="overflow-x:auto;">
                <thead>
                <tr>
                    <th>Vintage:</th>
                    <th>Description:</th>
                    <th>Price:</th>
                    <th>Available:</th>
                    {% if user.is_authenticated %}
                        {% if user.is_staff %}
                            <th>Update:</th>
                            <th>Delete:</th>
                        {% else %}
                            <th>Buy:</th>
                        {% endif %}
                    {% endif %}
                </tr>
            </thead>
            {% for vintage in product.productvintage_set.all|order_by:'vintage' %}
                <tr>
                    <td><a class="btn btn btn-outline-light" href="{% url 'shop:vintage_detail' vintage.id %}">{{ vintage.vintage }}</a></td>
                    <td title="{{ vintage.vintage_description }}">{{ vintage.vintage_description|truncatewords:15 }}</td>
                    <td>{{ vintage.price }} €</td>
                    {% if user.is_staff %}
                        {% with vintage.stock|difference:vintage.available_stock as avail_diff %}
                            <td>
                                <p>{{ vintage.available_stock }}</p>
                                {% if avail_diff %}<p><em>{{ avail_diff }} reserved</em></p>{% endif %}
                            </td>
                        {% endwith %}
                        <td><a class="btn btn btn-outline-light" href="{% url 'shop:vintage_update' vintage.id %}">Update</a></td>
                        <td><a class="btn btn btn-outline-warning" href="{% url 'shop:vintage_delete' vintage.id %}">Delete</a></td>
                    {% elif user.is_authenticated %}
                        <td>{{ vintage.available_stock }}</td>
                        <td><a class="btn btn btn-success" href="{% url 'shop:customer_order' product.id %}?vintage={{ vintage.id }}">Order</a></td>
                    {% else %}
                        <td>{{ vintage.available_stock }}</td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
    {% if user.is_staff %}
        <a class="btn btn-outline-light" style="margin: 20px; width: 80%;" href="{% url 'shop:vintage_create' %}?product={{ product.id }}">Add a new Vintage</a>
    {% endif %}
{% endblock %}